---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

# datalowSADocs

<!-- badges: start -->
<!-- badges: end -->

The goal of datalowSADocs is to provide simple access to the vignettes and the FRDC project report aimed at providing training courses in data-poor and data-moderate stock assessment methods (Reducing the Number of Undefined Species in Future Status of Australian Fish Stocks Reports: Phase Two - training in the assessment of data-poor stocks. FRDC Project 2017/102. See Haddon et al, 2019).

Once here in this repository perhaps the best way forward is to press the green "code" button and ask to 'download ZIP', which will download a 4.9Mb file containing all the files in the repository, which you can open in the usual way.

With contracts only being signed about one week before the first workshop happened up in Darwin, you need to remember that the package functions and the vignettes were written in rather a rush. I will be working on these to make improvements but this is not my primary focus currently. Nevertheless, if you end up with troubles while using this package do feel free to get in touch with me.


Malcolm Haddon

Hobart, Oct 2020

